backend:
  name: github
  repo: seanelliott86/personal-site
  branch: main
media_folder: "src/assets/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Hero Image",
          name: "hero",
          widget: "image",
          choose_url: false,
          allow_multiple: false,
          required: false,
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }

  # Resume Intro as a separate collection
  - name: "resume-intro"
    label: "Resume - Intro"
    delete: false
    files:
      - label: "Intro"
        name: "intro"
        file: "src/resume/intro.md"
        fields:
          - { label: "Body", name: "body", widget: "markdown" }

  # Resume Experience as its own collection
  - name: "resume-experience"
    label: "Resume - Experience"
    folder: "src/resume/experience"
    create: true
    slug: "{{fields.company}}-{{fields.startdate}}"
    summary: "{{company}} - {{startdate}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Company Name",
          name: "company",
          widget: "string",
          required: true,
        }
      - {
          label: "Current Role",
          name: "current-role",
          widget: "boolean",
          default: true,
          required: true,
          hint: "If this is FALSE make sure to specify an end date below",
        }
      - {
          label: "Start Date",
          name: "startdate",
          widget: "datetime",
          date_format: "MMMM YYYY",
          required: true,
        }
      - {
          label: "End Date",
          name: "enddate",
          widget: "datetime",
          date_format: "MMMM YYYY",
          required: false,
        }
      - {
          label: "Description",
          name: "body",
          widget: "markdown",
          required: true,
        }
